# Question 5 - two-parter

## Original code provided
```js
const team = {
  members:['Superman','Batman','Wonder Woman'],
  teamName: 'Justice league',
  teamSummary: function(){
    return this.members.map(function(member) {
    return `${member} is on team ${this.teamName}`;
    });
  }
 };
 team.teamSummary();
```

## i) Will the above code block return an error?

Whilst it doesn't return an _error_ (in the sense of throw / raise an actual javascript error), 
it will cause unexpected behaviour - it won't be able to access the `this.teamName` property,
and hence simply return `${member} is on team undefined` for each of the array elements.
Now `team undefined` would make a good team name, but we're talking Superman and Wonder Woman-league here.

## ii) If yes, then why and how do we fix it?

Is this a trick question? ;) There's no error thrown _per se_. However, the fix for the unexpected behaviour
described in part i would be to use an arrow function so that a new `this` context does not get created
when the inner function is created.


## Here is code that should work:

```js
const team = {
  members:['Superman','Batman','Wonder Woman'],
  teamName: 'Justice league',
  teamSummary: function(){
    // The following line, function as param in the `.map` is what caused unexpected behaviour,
    // fix is changing regular function `function ()` to arrow function `() =>`
    // The old way of doing this would have been assigning this to a variable before the function was created
    return this.members.map(member => {
      return `${member} is on team ${this.teamName}`;
    });
  }
 };

 team.teamSummary();
```


BONUS: How I'd streamline it:
```js
const team = {
  members: ['Superman', 'Batman', 'Wonder Woman'],
  teamName: 'Justice league',
  teamSummary () {
    return this.members.map(member => `${member} is on team ${this.teamName}`)
  }
};

team.teamSummary();
```
